# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages


r_github_packages: Zelazny7/isofor

install:
  - R -e 'install.packages("devtools")'
  - R -e 'devtools::install_deps(dependencies = TRUE)'
  - R -e 'devtools::install_version("randomForestSRC", "2.5.0")'
  - R -e 'devtools::install_github("alex23lemm/zementisr")'

after_success:
  - Rscript -e 'covr::codecov()'