# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

install:
  - R -e 'install.packages("devtools")'
  - R -e 'devtools::install_deps(dependencies = TRUE)'
  - R -e 'devtools::install_version("randomForestSRC", "2.5.0")'