# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

install:
  - Rscript -e 'install.packages("devtools")'
  - Rscript -e 'devtools::install_deps(dependencies = TRUE)'
  - Rscript -e 'devtools::install_version("randomForestSRC", "2.5.0")'
  - Rscript -e 'devtools::install_github("alex23lemm/zementisr")'
  - Rscript -e 'devtools::install_github("Zelazny7/isofor")'

after_success:
  - Rscript -e 'covr::codecov()'