# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

install:
  - R -e 'install.packages("remotes")'
  - R -e 'remotes::install_deps(dependencies = TRUE, upgrade = "always")'
  - R -e 'remotes::install_version("randomForestSRC", "2.5.0")'
  - R -e 'remotes::install_github("alex23lemm/zementisr")'
  - R -e 'remotes::install_github("Zelazny7/isofor")'

after_success:
  - Rscript -e 'covr::codecov()'
